### ISSUE TITLE
Mejora el botón para cambiar a modo Oscuro o Claro

### ISSUE THREAD

**Issue by collectivecloudperu** [collectivecloudperu/modo_oscuro_claro_mantener_modo_seleccionado#2]
El botón es básico y puedes intentar mejorarlo, podrías colocar un slide button para mejorar la UX de la aplicación. 

Estaré atento a tu contribución y podrás ganar los premios que ofrecen los organizadores  :1st_place_medal: 

[](https://hacktoberfest.digitalocean.com/ )

Nube Colectiva *

**Comment by mendoza** [comment]
Me encantaria ayudarte con este issue
Asignamelo por favor para ver que tan bonito lo podemos dejar

**Comment by collectivecloudperu** [comment]
> Me encantaria ayudarte con este issue
> Asignamelo por favor para ver que tan bonito lo podemos dejar

**Comment by collectivecloudperu** [comment]
> Me encantaria ayudarte con este issue
> Asignamelo por favor para ver que tan bonito lo podemos dejar

Listo ya te lo asigne @mendoza dale no te rindas sigamos adelante !

**Comment by collectivecloudperu** [comment]
Genial, gracias por participar :)
